###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    ####注册中心应用名称
    name: configserver
  cloud:
    config:
      server:
        git:
          ###git环境地址
          uri: https://gitee.com/lvoym/Order_SYS.git #git仓库地址
          ####搜索目录
          search-paths:
            - config
      ####读取分支
      label: master

####端口号
server:
  port: 8888
